export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const REGISTER_USERS_REQUEST = "REGISTER_USERS_REQUEST";
export const REGISTER_USERS_SUCCESS = "REGISTER_USERS_SUCCESS";
export const REGISTER_USERS_FAILURE = "REGISTER_USERS_FAILURE";
